<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
    <dict>

        <!-- Theme Name -->
        <key>name</key>
        <string>Fanuc TP</string>

        <!-- Scope Name -->
        <key>scopeName</key>
        <string>source.fanuctp</string>

        <!-- File Types -->
        <key>fileTypes</key>
        <array>
            <string>ls</string>
        </array>

        <key>uuid</key>
        <string>E07EC438-7B75-4437-8AA1-DB94AABBAAAA</string>

        <!-- https://stackoverflow.com/questions/33403324/how-to-create-a-simple-custom-language-colorization-to-vs-code -->
        <!-- FOR COLORS: http://manual.macromates.com/en/language_grammars -->
        <key>patterns</key>
        <array>


            <!-- Header -->
            <dict>
                <key>match</key>
                <string>(\/PROG).*\n</string>
                <key>name</key>
                <string>support.class</string>
            </dict>

            <!-- Register/Input -->
            <dict>
                <key>match</key>
                <string>P?V?A?S?R\[.*?\]\]*</string>
                <key>name</key>
                <string>support.variable</string>
            </dict>
            <dict>
                <key>match</key>
                <string>D?R?A?G?U?S?(I|O)\[.*?\]\]*</string>
                <key>name</key>
                <string>support.variable</string>
            </dict>
            <dict>
                <key>match</key>
                <string>P?F?\[.*?\]\]*</string>
                <key>name</key>
                <string>support.variable</string>
            </dict>
            <!-- Timer -->
            <dict>
                <key>match</key>
                <string>(TIMER)\[.*?\]\]*</string>
                <key>name</key>
                <string>keyword.control</string>
            </dict>

            <!-- Number -->
            <dict>
                <key>match</key>
                <string>\d(\s)*(\.)?(\s)*(%|mm|deg|cm|m|mm|sec)?(\/(min|sec))?</string>
                <key>name</key>
                <string>constant.numeric</string>
            </dict>
            <!-- ON/OFF -->
            <dict>
                <key>match</key>
                <string>(?<=\=)\s*(ON|OFF)</string>
                <key>name</key>
                <string>constant.language</string>
            </dict>

            <!-- Motion Instructions -->
            <dict>
                <key>match</key>
                <string>(?<=:)\s*(J|L|C|A)\s</string>
                <key>name</key>
                <string>invalid.illegal</string>
            </dict>
            <dict>
                <key>match</key>
                <string>(FINE|CNT\d*)\s*(INC)?(?=;)</string>
                <key>name</key>
                <string>invalid.illegal</string>
            </dict>
            <dict>
                <key>match</key>
                <string>(FINE|CNT\d*\s*(INC)?)\s*(OFFSET|VOFFSET|TOOL_OFFSET)?\s*(?=,)</string>
                <key>name</key>
                <string>invalid.illegal</string>
            </dict>

            <!-- comment -->
            <dict>
                <key>match</key>
                <string>\s*:\s*!.*;</string>
                <key>name</key>
                <string>comment.line</string>
            </dict>

            <!-- string -->
            <dict>
                <key>match</key>
                <string>\'.*\'</string>
                <key>name</key>
                <string>string.quoted</string>
            </dict>
             <dict>
                <key>match</key>
                <string>\".*\"</string>
                <key>name</key>
                <string>string.quoted</string>
            </dict>
            
            <!-- Start character -->
            <dict>
                <key>match</key>
                <string>^\s*:</string>
                <key>name</key>
                <string>constant.other</string>
            </dict>
            <!-- EVERYTHING AFTER START CHAR (?<=\:).* -->

            <!-- IF, THEN, ELSE, END, ENDIF,  -->
            <dict> 
                <key>match</key>
                <string>(?<=:)\s*(IF|FOR)(?=(\s|\())</string>
                <key>name</key>
                <string>keyword.control</string>
            </dict>
            <!-- IF, THEN, ELSE, END, ENDIF,  -->
            <dict> 
                <key>match</key>
                <string>(?<=:)\s*(ELSE|ENDIF|ENDFOR|END|ABORT)\s*(?=;)</string>
                <key>name</key>
                <string>keyword.control</string>
            </dict>
            <dict> 
                <key>match</key>
                <string>THEN\s*(?=;)</string>
                <key>name</key>
                <string>keyword.control</string>
            </dict>

            <!-- LBL -->
            <dict> 
                <key>match</key>
                <string>(JMP\s*)?LBL\[.+\](?=;)</string>
                <key>name</key>
                <string>keyword.control</string>
            </dict>

            <!-- WAIT/VISION-->
            <dict> 
                <key>match</key>
                <string>(?<=:)\s*(WAIT|VISION(\s*)(\S*)|FORCE(\s*)(\S*))</string>
                <key>name</key>
                <string>support.function</string>
            </dict>

            <!-- CALL -->
            <dict> 
                <key>match</key>
                <string>(CALL|RUN)\s+[a-zA-Z0-9_]*\(?</string>
                <key>name</key>
                <string>support.function</string>
            </dict>

            <!-- MESSAGE/UALM -->
            <dict> 
                <key>match</key>
                <string>(?<=:)\s*(MESSAGE|UALM)\[.*\]\s*(?=;)</string>
                <key>name</key>
                <string>support.function</string>
            </dict>


        </array>







    </dict>
</plist>
